export const events = [
  {
    id: "1",
    date: "21-02-2015",
    title: "Loss Harvest Documented",
    category: "Tax Loss Harvesting",
  },
  {
    id: "2",
    date: "23-02-2015",
    title: "Cryptocurrency Purchased",
    category: "Trading Events",
  },
  {
    id: "3",
    date: "24-02-2015",
    title: "Two-Factor Authentication Enabled",
    category: "Account Maintenance",
  },
  {
    id: "4",
    date: "06-04-2015",
    title: "Tax Savings Recognized",
    category: "Tax Loss Harvesting",
  },
  {
    id: "5",
    date: "30-09-2015",
    title: "Password Changed",
    category: "Account Maintenance",
  },
  {
    id: "6",
    date: "01-11-2015",
    title: "Tax Harvesting Scheduled",
    category: "Tax Loss Harvesting",
  },
  {
    id: "7",
    date: "20-01-2016",
    title: "Tax Harvest Order Placed",
    category: "Tax Loss Harvesting",
  },
  {
    id: "7",
    date: "20-01-2016",
    title: "Tax Harvest Order Placed",
    category: "Tax Loss Harvesting",
  },
  {
    id: "7",
    date: "20-01-2016",
    title: "Tax Harvest Order Placed",
    category: "Tax Loss Harvesting",
  },
  {
    id: "7",
    date: "22-01-2016",
    title: "Tax Harvest Order Placed",
    category: "Tax Loss Harvesting",
  },
  {
    id: "7",
    date: "23-01-2016",
    title: "Tax Harvest Order Placed",
    category: "Tax Loss Harvesting",
  },
  {
    id: "7",
    date: "25-01-2016",
    title: "Tax Harvest Order Placed",
    category: "Tax Loss Harvesting",
  },
  {
    id: "8",
    date: "22-02-2016",
    title: "Margin Call Triggered",
    category: "Trading Events",
  },
  {
    id: "8",
    date: "22-03-2016",
    title: "Margin Call Triggered",
    category: "Trading Events",
  },
  {
    id: "8",
    date: "22-04-2016",
    title: "Margin Call Triggered",
    category: "Trading Events",
  },
  {
    id: "8",
    date: "22-05-2016",
    title: "Margin Call Triggered",
    category: "Trading Events",
  },
  {
    id: "8",
    date: "22-06-2016",
    title: "Margin Call Triggered",
    category: "Trading Events",
  },
  {
    id: "9",
    date: "30-04-2016",
    title: "Account Suspended",
    category: "Account Maintenance",
  },
  {
    id: "10",
    date: "03-05-2016",
    title: "Harvest Opportunity Identified",
    category: "Tax Loss Harvesting",
  },
  {
    id: "11",
    date: "27-06-2016",
    title: "Harvest Rebalance Executed",
    category: "Tax Loss Harvesting",
  },
  {
    id: "12",
    date: "07-08-2016",
    title: "Tax Loss Sale Completed",
    category: "Tax Loss Harvesting",
  },
  {
    id: "13",
    date: "11-11-2016",
    title: "Margin Account Opened",
    category: "Account Maintenance",
  },
  {
    id: "14",
    date: "13-12-2016",
    title: "Loss Swap Completed",
    category: "Tax Loss Harvesting",
  },
  {
    id: "15",
    date: "17-01-2017",
    title: "Tax-Loss Benefit Applied",
    category: "Tax Loss Harvesting",
  },
  {
    id: "16",
    date: "19-02-2017",
    title: "Funds Withdrawn",
    category: "Trading Events",
  },
  {
    id: "17",
    date: "26-05-2017",
    title: "Stop Loss Triggered",
    category: "Trading Events",
  },
  {
    id: "18",
    date: "05-09-2017",
    title: "Tax Reporting Updated",
    category: "Tax Loss Harvesting",
  },
  {
    id: "19",
    date: "25-09-2017",
    title: "Dividend Reinvested",
    category: "Trading Events",
  },
  {
    id: "20",
    date: "03-11-2017",
    title: "Beneficiary Added",
    category: "Account Maintenance",
  },
  {
    id: "21",
    date: "13-01-2018",
    title: "Stock Split Occurred",
    category: "Trading Events",
  },
  {
    id: "22",
    date: "18-03-2018",
    title: "Dividend Received",
    category: "Trading Events",
  },
  {
    id: "23",
    date: "15-09-2018",
    title: "Phone Number Updated",
    category: "Account Maintenance",
  },
  {
    id: "24",
    date: "15-09-2018",
    title: "Tax Loss Recorded",
    category: "Tax Loss Harvesting",
  },
  {
    id: "25",
    date: "21-10-2018",
    title: "Stop Loss Triggered",
    category: "Trading Events",
  },
  {
    id: "26",
    date: "05-12-2018",
    title: "Loss Harvest Documented",
    category: "Tax Loss Harvesting",
  },
  {
    id: "27",
    date: "24-02-2019",
    title: "Beneficiary Removed",
    category: "Account Maintenance",
  },
  {
    id: "28",
    date: "11-03-2019",
    title: "Loss Realization Reported",
    category: "Tax Loss Harvesting",
  },
  {
    id: "29",
    date: "01-01-2020",
    title: "Account Settings Updated",
    category: "Account Maintenance",
  },
  {
    id: "29",
    date: "01-01-2020",
    title: "Account Settings Updated",
    category: "Account Maintenance",
  },
  {
    id: "30",
    date: "01-01-2020",
    title: "Order Placed",
    category: "Trading Events",
  },
  {
    id: "30",
    date: "01-01-2020",
    title: "Order Placed",
    category: "Trading Events",
  },
  {
    id: "31",
    date: "15-03-2020",
    title: "Portfolio Rebalanced for Tax Loss Harvesting",
    category: "Tax Loss Harvesting",
  },
  {
    id: "32",
    date: "30-08-2020",
    title: "Email Address Updated",
    category: "Account Maintenance",
  },
  {
    id: "33",
    date: "17-11-2020",
    title: "Limit Order Placed",
    category: "Trading Events",
  },
  {
    id: "34",
    date: "05-05-2021",
    title: "Account Tier Upgraded",
    category: "Account Maintenance",
  },
  {
    id: "35",
    date: "12-06-2021",
    title: "Account Profile Updated",
    category: "Account Maintenance",
  },
  {
    id: "36",
    date: "12-06-2021",
    title: "Trade Executed",
    category: "Trading Events",
  },
  {
    id: "37",
    date: "12-06-2021",
    title: "Tax Loss Harvest Executed",
    category: "Tax Loss Harvesting",
  },
  {
    id: "38",
    date: "23-07-2021",
    title: "Funds Deposited",
    category: "Trading Events",
  },
  {
    id: "39",
    date: "19-10-2021",
    title: "Address Changed",
    category: "Account Maintenance",
  },
  {
    id: "40",
    date: "05-11-2021",
    title: "Capital Gain Offset Computed",
    category: "Tax Loss Harvesting",
  },
  {
    id: "41",
    date: "20-01-2022",
    title: "Email Verification Completed",
    category: "Account Maintenance",
  },
  {
    id: "42",
    date: "04-09-2022",
    title: "Security Question Updated",
    category: "Account Maintenance",
  },
  {
    id: "43",
    date: "02-01-2023",
    title: "Trade Cancelled",
    category: "Trading Events",
  },
  {
    id: "44",
    date: "27-03-2023",
    title: "Two-Factor Authentication Disabled",
    category: "Account Maintenance",
  },
  {
    id: "45",
    date: "30-08-2023",
    title: "Tax Lot Adjusted",
    category: "Tax Loss Harvesting",
  },
  {
    id: "46",
    date: "21-09-2023",
    title: "Deposits Processed",
    category: "Account Maintenance",
  },
  {
    id: "47",
    date: "13-11-2023",
    title: "Short Position Opened",
    category: "Trading Events",
  },
  {
    id: "48",
    date: "13-02-2024",
    title: "Loss Realization Reported",
    category: "Tax Loss Harvesting",
  },
  {
    id: "49",
    date: "16-02-2024",
    title: "Stop Loss Triggered",
    category: "Trading Events",
  },
  {
    id: "50",
    date: "08-04-2024",
    title: "Account Statement Generated",
    category: "Account Maintenance",
  },
  {
    id: "51",
    date: "10-04-2024",
    title: "Trade Cancelled",
    category: "Trading Events",
  },
  {
    id: "52",
    date: "11-07-2024",
    title: "Dividend Reinvested",
    category: "Trading Events",
  },
  {
    id: "53",
    date: "27-08-2024",
    title: "KYC Verified",
    category: "Account Maintenance",
  },
  {
    id: "54",
    date: "11-11-2024",
    title: "Funds Withdrawn",
    category: "Trading Events",
  },
  {
    id: "55",
    date: "30-11-2024",
    title: "Account Created",
    category: "Account Maintenance",
  },
  {
    id: "56",
    date: "25-04-2025",
    title: "Capital Loss Realized",
    category: "Tax Loss Harvesting",
  },
  {
    id: "57",
    date: "25-04-2025",
    title: "Cash Withdrawal Processed",
    category: "Tax Loss Harvesting",
  },
  {
    id: "58",
    date: "27-10-2025",
    title: "Position Opened",
    category: "Trading Events",
  },
  {
    id: "59",
    date: "01-11-2025",
    title: "Account Closed",
    category: "Account Maintenance",
  },
  {
    id: "60",
    date: "30-12-2025",
    title: "Stock Split Occurred",
    category: "Trading Events",
  },
  {
    id: "60",
    date: "30-12-2025",
    title: "Stock Split Occurred",
    category: "Trading Events",
  },
  {
    id: "60",
    date: "30-12-2025",
    title: "Stock Split Occurred",
    category: "Trading Events",
  },
  {
    id: "60",
    date: "30-12-2025",
    title: "Stock Split Occurred",
    category: "Trading Events",
  },
  {
    id: "60",
    date: "30-12-2025",
    title: "Stock Split Occurred",
    category: "Trading Events",
  },
];
